---
- name: Get list of regular users
  hosts: all
  become: false
  tasks:
    - name: Get list of all users
      shell: "getent passwd | awk -F: '$3>=1000 && $3<65534 { print $1 }' | sort"
      register: user_list
      
    - name: Display list of regular users
      debug:
        var: user_list.stdout_lines
