---
- name: Get list of regular users with group membership and password expiration date
  hosts: your_host
  become: false
  tasks:
    - name: Get list of all users
      shell: "getent passwd | awk -F: '$3>=1000 && $3<65534 { print $1 }' | sort"
      register: user_list

    - name: Get user details
      shell: "for user in $(echo {{ user_list.stdout }}); do groups $user; chage -l $user; done"
      register: user_details

    - name: Display user details
      debug:
        var: user_details.stdout_lines

