---
- name: Get list of all users
  hosts: all
  tasks:
    - name: Get list of all users
      shell: "cut -d: -f1 /etc/passwd | sort"
      register: user_list
      
    - name: Display list of users
      debug:
        var: user_list.stdout_lines
